repeat_count: 1
repeat_delay: 0.5
speed_percent: 100.0
selected_recording: recordings/daily_1.yaml
events:
- time: 1.078248
  action: key_down
  key: right
- time: 1.409789
  action: key_down
  key: up
- time: 1.483752
  action: key_up
  key: right
- time: 2.754325
  action: key_up
  key: up
